// Code generated by templ - DO NOT EDIT.

// templ: version: v0.3.819
package uploadView

//lint:file-ignore SA4006 This context is only used if a nested component is present.

import "github.com/a-h/templ"
import templruntime "github.com/a-h/templ/runtime"

import "github.com/harryparsons-dev/go-shares/views/layout"
import "github.com/harryparsons-dev/go-shares/views/components"
import "github.com/harryparsons-dev/go-shares/models"

func Show(user models.User) templ.Component {
	return templruntime.GeneratedTemplate(func(templ_7745c5c3_Input templruntime.GeneratedComponentInput) (templ_7745c5c3_Err error) {
		templ_7745c5c3_W, ctx := templ_7745c5c3_Input.Writer, templ_7745c5c3_Input.Context
		if templ_7745c5c3_CtxErr := ctx.Err(); templ_7745c5c3_CtxErr != nil {
			return templ_7745c5c3_CtxErr
		}
		templ_7745c5c3_Buffer, templ_7745c5c3_IsBuffer := templruntime.GetBuffer(templ_7745c5c3_W)
		if !templ_7745c5c3_IsBuffer {
			defer func() {
				templ_7745c5c3_BufErr := templruntime.ReleaseBuffer(templ_7745c5c3_Buffer)
				if templ_7745c5c3_Err == nil {
					templ_7745c5c3_Err = templ_7745c5c3_BufErr
				}
			}()
		}
		ctx = templ.InitializeContext(ctx)
		templ_7745c5c3_Var1 := templ.GetChildren(ctx)
		if templ_7745c5c3_Var1 == nil {
			templ_7745c5c3_Var1 = templ.NopComponent
		}
		ctx = templ.ClearChildren(ctx)
		templ_7745c5c3_Err = layout.Base().Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = components.Navbar(user).Render(ctx, templ_7745c5c3_Buffer)
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		templ_7745c5c3_Err = templruntime.WriteString(templ_7745c5c3_Buffer, 1, "<form id=\"create-export\" hx-post=\"/exports\" hx-target=\"#response\" hx-swap=\"innerHTML\" enctype=\"multipart/form-data\"><h2>Create an export:</h2><label for=\"file\">Choose a CSV</label> <input type=\"file\" id=\"file\" name=\"file\" required><br><br><label for=\"title\">Title:</label> <input type=\"text\" id=\"title\" name=\"title\" required><br><br><label for=\"font_size\">Font size:</label> <input type=\"text\" id=\"font_size\" name=\"font_size\" required><br><br><label for=\"padding\">Padding</label> <input type=\"text\" id=\"padding\" name=\"padding\" required><br><br><button type=\"submit\">Upload</button></form><div id=\"response\"></div>")
		if templ_7745c5c3_Err != nil {
			return templ_7745c5c3_Err
		}
		return nil
	})
}

var _ = templruntime.GeneratedTemplate
